- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/Design.md
Add design document
Add code of conduct
Add info on contributing
Add CODEOWNERS file
> Add initial documentation

- .github/CODEOWNERS
- README.md
Add code owners file to auto-fill in github reviewers
> Add CODEOWNERS file

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Core/State.cs
- OrcanodeMonitor/OrcanodeMonitor.csproj
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Properties/PublishProfiles/OrcanodeMonitor - Web Deploy.pubxml
- OrcanodeMonitor/Properties/ServiceDependencies/OrcanodeMonitor - Web Deploy/profile.arm.json
Display times in Pacific time not UTC
> Display times in Pacific time not UTC

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/OrcanodeEvent.cs
Display recent events in Pacific time
> Display recent events in Pacific time

- .github/workflows/publish.yml
> Add GitHub workflow to publish to Azure on push

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/OrcanodeEvent.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Core/State.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
- docs/Design.md
> Add support for querying dataplicity for status

- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/OrcanodeEvent.cs
- OrcanodeMonitor/Core/State.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Fixed Orcasound status column
And will now only display the Listen button for nodes listed on Orcasound
> Fix dashboard columns

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
Show agent version and disk usage
> Show agent version and disk usage

- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Pages/Index.cshtml
- docs/Design.md
ORCASOUND_MAX_UPLOAD_DELAY_MINUTES
ORCASOUND_POLL_FREQUENCY_IN_MINUTES
Fixes #15
Also change "Orcasound Status" label to "Stream Status" per Scott's recommendation
> Add more configuration settings

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
- docs/Design.md
> Show last OrcaHello detection

- OrcanodeMonitor/Api/NodeStateEventsController.cs
- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/Orcanode.cs
- OrcanodeMonitor/Core/OrcanodeEvent.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Core/State.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Models/OrcanodeEvent.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Update state model to update info as it comes in, rather than once all queries are complete
> Show data as soon as it is available

- .github/workflows/release.yml
Fix workflow that runs on every push to update the staging app
Add workflow to update the production app when a tag is pushed that makes a semver pattern like "v0.1.0"
Fixes #33
> Update deployment workflows

- .github/workflows/build.yml
- .github/workflows/publish.yml
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.css
- docs/Design.md
* Add staging server to Design.md
* Update the staging server publish workflow label
* Remove harden-runner from Windows workflow since it only supports Ubuntu
* Update font size on main web page
> Minor tweaks and doc updates

- OrcanodeMonitor/Models/Orcanode.cs
> Fix stream status for absent streams

- OrcanodeMonitor/Pages/Index.cshtml.cs
> Alphabetize nodes in table

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
* Don't make new queries to orcahello
* Comment out columns from web page that show last orcahello detection
* Leave the columns in the SQL database to avoid a migration
Fixes #43
> Disable OrcaHello querying for now

- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
To match download-artifact which dependabot just bumped
> Bump actions/upload-artifact to v4

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/OrcanodeEvent.cs
in preparation for addiing other event types
> Tweak event description

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Models/OrcanodeEvent.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Add events for:
* dataplicity connection status
* agent upgrade available
* disk capacity change
Also change "stream status" to "hydrophone stream" in description of existing events, to be more specific.
Fixes #45
> Add additional events

- OrcanodeMonitor/Migrations/20240618154107_InitialCreate.cs
- OrcanodeMonitor/Program.cs
See https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-8.0&tabs=visual-studio
> Use migrations not EnsureCreated

- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
> Apply usability feedback

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/PeriodicTasks.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Derive S3 default node name from dataplicity name
> Check S3 even if orcasound doesn't know about a node

- OrcanodeMonitor/Program.cs
- OrcanodeMonitor/appsettings.Development.json
> Use local SQL database unless envar is set

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Migrations/OrcanodeMonitorContextModelSnapshot.cs
- OrcanodeMonitor/Models/Orcanode.cs
> Store orcasound feed ID

- OrcanodeMonitor/Models/OrcanodeEvent.cs
> Fix IFTTT message

- OrcanodeMonitor/appsettings.json
- docs/Design.md
> Set Pooling to False

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Migrations/OrcanodeMonitorContextModelSnapshot.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml.cs
- docs/Debugging.md
Also:
* Make the node DisplayName be derived rather than stored
* Add migration to remove DisplayName column
* Display the full DisplayName without trimming the "at"
Addresses #82
> Handle merging dataplicity node and orcasound node

- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Program.cs
- OrcanodeMonitor/Properties/launchSettings.json
> Clean up migration code

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Migrations/OrcanodeMonitorContextModelSnapshot.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml.cs
> Add Orcasite "hidden" status

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
* Set Dataplicity status to Absent for a node that is not returned by dataplicity (addresses part of #114)
* Update legend (fixes #113)
* Fix bug when a node is on dataplicity but not orcasite
> Add Dataplicity Absent status

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Also, S3 stream should show Absent for non-existent streams
Fixes #114
Fixes #115
> Hide nodes that are Absent at dataplicity, orcasound, and S3

- OrcanodeMonitor/Pages/Index.cshtml
> Fix link to OrcaHello

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
Also update a SQL comment for clarity
> Update monitor state timestamp when dataplicity or orcasite data changes

- OrcanodeMonitor/Program.cs
Make cosmos database name configurable via the AZURE_COSMOS_DATABASENAME environment variable
> Make cosmos database name configurable

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/JsonFormatter.cs
- OrcanodeMonitor/Pages/DataplicityNode.cshtml
- OrcanodeMonitor/Pages/DataplicityNode.cshtml.cs
- OrcanodeMonitor/Pages/Index.cshtml
> Add ability to see dataplicity state for each node

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
> Show dev nodes on dashboard

- OrcanodeMonitor/Pages/Index.cshtml
- OrcanodeMonitor/Pages/Index.cshtml.cs
Display dev nodes after prod nodes
> Fix node sort order on dashboard

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Models/Orcanode.cs
- OrcanodeMonitor/Pages/Index.cshtml
* Show S3 status even if orcasite doesn't know about the node
* Add Unauthorized as an S3 stream status
* Fix URL in S3 stream column links
Fixes #134
> Show S3 status even if orcasite doesn't know about the node

- OrcanodeMonitor/Pages/Index.cshtml
> Add Unauthorized to legend

- OrcanodeMonitor/Core/Fetcher.cs
> Fix OrcaHello status column

- OrcanodeMonitor/Pages/Index.cshtml.cs
Previously only hid rows that were all Absent
Fixes #156
> Hide rows that are Absent+Unauthorized

- OrcanodeMonitor/Models/OrcanodeEvent.cs
> Add severity member in IFTTT event api

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/validate-yaml.yml
- .pre-commit-config.yaml
- .yamllint.yml
Add CI/CD workflow to validate YAML changes
> Add yamllint checks

- OrcanodeMonitor/Core/Fetcher.cs
- OrcanodeMonitor/Core/FrequencyInfo.cs
- OrcanodeMonitor/OrcanodeMonitor.csproj
- OrcanodeMonitor/Pages/SpectralDensity.cshtml
- OrcanodeMonitor/Pages/SpectralDensity.cshtml.cs
- docs/Design.md
* Use fftsharp
* Display decibels instead of magnitude
* Configure thresholds using decibels instead of magnitude
> Update FFT algorithm
